Fixed In-progress Application Removal On Exit Button Click
opencrvs/opencrvs-core pull request #2287
Opened 2021-11-11 07:22 UTC by sadmananik

![Fixed for remove application from progress bar on exit](https://user-images.githubusercontent.com/36187489/141255506-92d83c1c-8d2f-4b22-bd3d-359d46b6b9d4.gif)

2021-11-22 07:32 UTC, sadmananik commented
Only changing the Zambia resource repository will solve this issue.

2021-11-22 08:03 UTC, sadmananik commented
Modified Exit button logic for the in-progress application.

2021-11-24 15:32 UTC, euanmillar requested changes
The Logic is correct, but if this is true:

```
application.submissionStatus === SUBMISSION_STATUS.DRAFT && application.review
```

Then the label should change from "EXIT" to "Save & Exit" because if you click it, the number change is saved

2021-11-29 14:22 UTC, euanmillar approved these changes

2021-11-29 14:22 UTC, merged