input field max width set to 344px
opencrvs/opencrvs-core pull request #2349
Opened 2021-12-15 05:50 UTC by emon-swe-sust

width on **'Weight at birth'** was fixed on 2129 ticket
width on **date of birth** was fixed on 2130 ticket

![width_344](https://user-images.githubusercontent.com/43314141/146130865-3d8ede13-049e-4a18-88de-c37756839631.gif)

2021-12-31 06:12 UTC, Zangetsu101 requested changes
![image](https://user-images.githubusercontent.com/29002716/147806699-52d04003-a157-4289-b102-54b03da127b7.png)
The Health Institution Field width needs to be 344px too.

2021-12-31 08:53 UTC, emon-swe-sust commented
> ![image](https://user-images.githubusercontent.com/29002716/147806699-52d04003-a157-4289-b102-54b03da127b7.png) The Health Institution Field width needs to be 344px too.

resolved ti !

2021-12-31 11:38 UTC, Zangetsu101 approved these changes

2022-01-05 18:04 UTC, euanmillar approved these changes

2022-01-05 18:04 UTC, merged