ocrvs-2397 Fixed the gen:types script
opencrvs/opencrvs-core pull request #2398
Opened 2022-01-04 07:47 UTC by Zangetsu101

2022-01-05 19:43 UTC, euanmillar requested changes
@Zangetsu101 there is a conflict in package.json.  Please explain what is the issue and how this PR fixes the issue

2022-01-06 05:57 UTC, Zangetsu101 commented
@euanmillar please take a look at #2397 and let's have a discussion if you still have any questions.

2022-01-13 18:27 UTC, euanmillar approved these changes

2022-01-13 18:34 UTC, euanmillar approved these changes

2022-01-13 18:35 UTC, merged