Ocrvs 2589 Print PDF certifcate from svg content from config
opencrvs/opencrvs-core pull request #2626
Opened 2022-02-25 07:56 UTC by tahmidrahman-dsi

2022-03-02 14:22 UTC, euanmillar commented on packages/client/src/offline/reducer.ts
> +          templates: action.payload.templates
@tahmidrahman-dsi see my comment in the Farajaland repo regarding the templates

2022-03-02 14:35 UTC, euanmillar requested changes
@tahmidrahman-dsi Altogether this is great work and nearly there.  However, I think that we should refactor templates away from farajaland entirely. See my comments in that PR.  Also, are we still using the printReducer?  I dont think so looking at the code.  Can you delete this please, along with the PDFViewer component, the PDF_DOCUMENT_VIEWER field type and the package react-pdf from the component library?  I think these are legacy but I may be mistaken.    Please also respond to JPF's alignment bug.

2022-03-03 07:50 UTC, tahmidrahman-dsi commented
> <img alt="image" width="711" src="https://user-images.githubusercontent.com/46478402/156334210-9ae1269f-bad5-4fea-b4e2-d1aa3527a1e2.png">
> 
> * Need to check the cantering on all copy.
> * Have 'at' on the first line for the place of registration

@jpye-finch can you please check if the issues have been resolved?

![image](https://user-images.githubusercontent.com/42269993/156520191-69ae8349-99b0-4d67-97b2-fa4c93b2d104.png)

2022-03-03 12:51 UTC, tahmidrahman-dsi commented
> @tahmidrahman-dsi Altogether this is great work and nearly there. However, I think that we should refactor templates away from farajaland entirely. See my comments in that PR. Also, are we still using the printReducer? I dont think so looking at the code. Can you delete this please, along with the PDFViewer component, the PDF_DOCUMENT_VIEWER field type and the package react-pdf from the component library? I think these are legacy but I may be mistaken. Please also respond to JPF's alignment bug.

Thanks Euan. I think we are still using `printReducer` and I agree`PDF_VIEWER` in `FormFieldGenerator` is no longer used, we can get rid of it. I  will do the requested the changes

2022-03-03 13:29 UTC, jpye-finch commented
@tahmidrahman-dsi looks good!

Will want to test the flow myself. Creating the svg. and adding the handles. May want to update the default certificate svg after that. 

As discussed on this morning call. The country logo should be in the certificate svg. As it will be printed it need to be high res. I need to come up with a logo for Farajaland!

2022-03-31 08:07 UTC, euanmillar approved these changes

2022-03-31 08:07 UTC, merged