Ocrvs 2564
opencrvs/opencrvs-core pull request #2700
Opened 2022-03-09 05:54 UTC by emon-swe-sust

2022-03-11 04:17 UTC, emon-swe-sust commented on packages/client/src/views/SysAdmin/Config/Application.tsx
> +            </div>
no, I changed it !

2022-03-11 08:08 UTC, Zangetsu101 commented on packages/components/src/components/icons/Cross.tsx
> +      fill = '#D53F3F'
Maybe we can use the color from `colors.ts`?

2022-03-11 12:20 UTC, atiqzaman-dsi requested changes

2022-03-11 12:20 UTC, atiqzaman-dsi commented on packages/client/src/utils/validate.ts
>      return undefined
`duplicateIDNumber` will have to be changed.
`if (value && valueToCheck && +value === +valueToCheck) ` Change this line.

2022-03-15 09:32 UTC, atiqzaman-dsi commented on packages/client/src/utils/validate.ts
>      return undefined
This code can be found in latest `develop` branch. @emon-swe-sust please test the `duplicateIDNumber` in `correct record`.

2022-03-15 13:17 UTC, closed without merging