OCRVS-2897: Render ConfigPlaceholder
opencrvs/opencrvs-core pull request #2980
Opened 2022-05-01 08:34 UTC by yeasinhossain-dsi

2022-05-01 09:10 UTC, Zangetsu101 commented
@yeasinhossain-dsi I'm not sure how this will affect moving the fields and also creating the `IQuestionConfig` payload afterwards

2022-05-01 09:55 UTC, yeasinhossain-dsi commented
> @yeasinhossain-dsi I'm not sure how this will affect moving the fields and also creating the `IQuestionConfig` payload afterwards

yeah, good thinking. i would have to make change so that moving a card will find the end of preview group & place it properly. Just talked with @euanmillar

2022-05-09 06:05 UTC, Zangetsu101 requested changes

2022-05-09 06:05 UTC, Zangetsu101 commented on packages/client/src/forms/configuration/formConfig/reducer.ts
> +function shiftUp(fieldMap: IConfigFieldMap, fieldId: string) {
I'm quite confused about what this function does. Maybe it would be a good idea to discuss it in detail

2022-05-09 06:05 UTC, Zangetsu101 commented on packages/client/src/components/formConfig/Canvas.tsx
> +    getRegisterFormSection(store, section, event)
We will need to use `selectConfigRegisterForm` instead as the dependecy on register reducer was removed in https://github.com/opencrvs/opencrvs-core/pull/2780/commits/c9544116baede952e584dd75edb4f284273f8a32

2022-05-09 08:13 UTC, merged