ocrvs 3471: Photo Spinning Issue
opencrvs/opencrvs-core pull request #3485
Opened 2022-06-15 07:26 UTC by soumita-dsi

2022-06-15 11:20 UTC, euanmillar requested changes
@soumita-dsi I have been thinking about this.  Is there any way to disable keyboard interaction with the image preview library entirely?  This fix will not stop the image from rotating when the key is pressed in all cases.

2022-06-15 11:24 UTC, Zangetsu101 commented
Are you talking about removing the keybindings entirely? @euanmillar

2022-06-15 11:55 UTC, euanmillar commented
@Zangetsu101 yes.  While they are a nice feature, I dont think we need them.  They were never a design requirement.

2022-06-16 07:38 UTC, rikukissa approved these changes

2022-06-16 11:02 UTC, merged