ocrvs-3454 Persisted the country logo in localStorage
opencrvs/opencrvs-core pull request #3646
Opened 2022-07-12 07:11 UTC by Zangetsu101

Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/317
![3454](https://user-images.githubusercontent.com/29002716/178429841-14035bc6-708b-4933-8955-b8276055c39e.gif)

2022-07-12 07:28 UTC, sadmananik requested changes

2022-07-12 07:28 UTC, sadmananik commented on packages/login/src/views/StepOne/StepOneForm.tsx
> +    localStorage.getItem('country-logo')
```suggestion
    localStorage.getItem('country-logo') ?? ''
```

2022-07-12 07:28 UTC, sadmananik commented on packages/login/src/views/StepOne/StepOneForm.tsx
> +  return offlineLogo ?? ''
```suggestion
  return offlineLogo
```

2022-07-12 07:28 UTC, sadmananik commented on packages/login/src/views/StepOne/StepOneForm.tsx
> +function usePersistentLogo() {
```suggestion
function usePersistentCountryLogo() {
```

2022-07-20 07:35 UTC, rikukissa approved these changes

2022-07-25 05:45 UTC, sadmananik approved these changes

2022-07-25 05:45 UTC, merged