ocrvs-3606 Replace CRA with Vite
opencrvs/opencrvs-core pull request #3653
Opened 2022-07-13 15:36 UTC by sadmananik

2022-07-15 04:38 UTC, Zangetsu101 requested changes

2022-07-15 04:38 UTC, Zangetsu101 commented on setup.sh
>    echo "nvm install 14.17.0"
14.18.0

2022-07-18 07:42 UTC, rikukissa commented
I noticed this in Vite output btw:

```
@opencrvs/client: 10:28:45 [vite] warning: Comparison using the "===" operator here is always false
@opencrvs/client: 395|    typeMapper?: any
@opencrvs/client: 396|  ) {
@opencrvs/client: 397|    if (draftData[sectionId][field.name] === []) {
@opencrvs/client:    |                                         ^
@opencrvs/client: 398|      return transformedData
@opencrvs/client: 399|    }
@opencrvs/client:   Plugin: vite:esbuild
@opencrvs/client:   File: /Users/riku/Code/OpenCRVS/opencrvs-core/packages/client/src/forms/mappings/mutation/field-mappings.ts
```

2022-07-19 09:52 UTC, sadmananik commented
> I noticed this in Vite output btw:
> 
> ```
> @opencrvs/client: 10:28:45 [vite] warning: Comparison using the "===" operator here is always false
> @opencrvs/client: 395|    typeMapper?: any
> @opencrvs/client: 396|  ) {
> @opencrvs/client: 397|    if (draftData[sectionId][field.name] === []) {
> @opencrvs/client:    |                                         ^
> @opencrvs/client: 398|      return transformedData
> @opencrvs/client: 399|    }
> @opencrvs/client:   Plugin: vite:esbuild
> @opencrvs/client:   File: /Users/riku/Code/OpenCRVS/opencrvs-core/packages/client/src/forms/mappings/mutation/field-mappings.ts
> ```

Fixed

2022-07-27 12:02 UTC, yeasinhossain-dsi commented
seems fine to me

2022-07-28 07:23 UTC, rikukissa commented on packages/client/vite.config.js
> +        if (code.match(/eval\(/)) return { moduleSideEffects: 'no-treeshake' }
Nice 👍

2022-07-28 08:56 UTC, merged