ocrvs-3489: Add/fix the media queries for createPin page, certificate…
opencrvs/opencrvs-core pull request #3679
Opened 2022-07-26 08:30 UTC by rabiulislamanik

… preview page and reviewAction page

2022-07-28 07:09 UTC, Zangetsu101 commented
![image](https://user-images.githubusercontent.com/29002716/181443046-732a5b4d-7020-466a-9503-72823eba565f.png)
The logout button is still overlapping

2022-07-28 07:10 UTC, Zangetsu101 requested changes
![image](https://user-images.githubusercontent.com/29002716/181443046-732a5b4d-7020-466a-9503-72823eba565f.png)
The logout button is still overlapping

2022-07-29 11:14 UTC, rabiulislamanik commented
> ![image](https://user-images.githubusercontent.com/29002716/181443046-732a5b4d-7020-466a-9503-72823eba565f.png) The logout button is still overlapping

Fixed it

2022-08-01 08:40 UTC, Zangetsu101 approved these changes

2022-08-01 08:57 UTC, merged