Auto-generate different shades of colour palette and document it in Storybook
opencrvs/opencrvs-core pull request #3779
Opened 2022-08-12 07:43 UTC by naftis

2022-08-15 20:38 UTC, naftis commented on packages/components/src/stories/colors.stories.mdx
> +? do we wanna include gradient here
todo

2022-08-17 06:27 UTC, Zangetsu101 reviewed
Looks good. Just wondering could we perhaps use `hsl` instead to create the lighter and darker shades?

2022-08-17 08:28 UTC, naftis commented
@Zangetsu101 Good idea.

@jpye-finch what do you think, could HSL work for our color system? Then we could just adjust the lightness of the color. This would mean that theme colors would need to be in HSL in future installations too

2022-08-19 09:49 UTC, Zangetsu101 commented
It seems not all the colors are rendering properly.
![image](https://user-images.githubusercontent.com/29002716/185593190-3e601a4f-490b-4841-8c82-f368746aaba3.png)

2022-08-22 07:37 UTC, naftis commented
@Zangetsu101 for me it flashed like that for a couple of seconds, but then started working properly, maybe the component library was still compiling on your end?
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/1322608/185865571-0d8fb927-30ac-449b-8561-480f87fd4768.png">

2022-08-22 08:27 UTC, Zangetsu101 commented
> @Zangetsu101 for me it flashed like that for a couple of seconds, but then started working properly, maybe the component library was still compiling on your end? Also fixed the issue with fonts not loading on the left side panel <img alt="image" width="1125" src="https://user-images.githubusercontent.com/1322608/185865571-0d8fb927-30ac-449b-8561-480f87fd4768.png">

Alright. Then it's fine.

2022-08-22 08:34 UTC, jpye-finch commented on packages/components/.storybook/preview.tsx
> -
@Zangetsu101 good idea! Still working on trying to get Noto Sans uses in the Storybook canvas for Headings.  

but we should set ourselves up to support a localisation addon i18n in the future

2022-08-23 06:40 UTC, Zangetsu101 requested changes
The changes look good. It's just that the the color palette doesn't load properly if you run storybook with the `yarn storybook` command but it works with `yarn start`.

2022-08-23 08:11 UTC, Zangetsu101 approved these changes

2022-08-23 08:29 UTC, merged