Ocrvs 3636 - As a National Registrar / National Sys Admin I want to view available VS exports
opencrvs/opencrvs-core pull request #4012
Opened 2022-09-29 10:13 UTC by CornelMaze

- adds sub menu option to Performance for National Registrar and National Sys Admin . Dashboard and Reports
- adds Reports page

2022-09-30 13:16 UTC, Zangetsu101 requested changes
@CornelMaze Could you remove the the csv files that were added with this PR as well please?

2022-09-30 13:52 UTC, CornelMaze commented on packages/gateway/src/features/metrics/schema.graphql
> +}
> We know that we will have these fields present so let's make them required and not optional

Ok. I would effect the changes.

2022-09-30 13:54 UTC, CornelMaze commented on packages/gateway/src/features/metrics/schema.graphql
> +}
> VSExport

Ok. Would effect this too

2022-10-04 07:58 UTC, Zangetsu101 requested changes
We also need a PR in farajaland with the new messages that were added.

2022-10-04 07:58 UTC, Zangetsu101 commented on packages/client/src/views/SysAdmin/Performance/Vsexports/VSExport.tsx
> +}
We won't need this anymore because we can reuse the type generated in the `gateway.ts` file

2022-10-04 07:58 UTC, Zangetsu101 commented on packages/client/src/views/SysAdmin/Performance/Vsexports/VSExport.tsx
> +function BirthTabContent(props: any) {
Could we try to type this properly instead of any please?

2022-10-04 07:58 UTC, Zangetsu101 commented on packages/client/src/i18n/messages/views/config.ts
> +    defaultMessage: 'Visual statistics export',
```suggestion
    defaultMessage: 'Vital statistics export',
```

2022-10-04 07:58 UTC, Zangetsu101 commented on packages/client/src/components/interface/Navigation.tsx
> +    )
Do we need this anymore?

2022-10-04 07:58 UTC, Zangetsu101 commented on packages/client/src/components/interface/Navigation.tsx
> +    WORKQUEUE_TABS.dashboard,
The `dasboard` is not needed anymore right?

2022-10-04 07:58 UTC, Zangetsu101 commented on packages/client/src/components/interface/Navigation.tsx
> +  const [isPerformExpanded, setIsPerformExpanded] = React.useState(false)
We don't need the expand feature anymore right?

2022-10-13 04:49 UTC, merged