ocrvs-4004: Add a constant 'ENABLE_REVIEW_SCROLL' and prevent scrolling of documents in document review section
opencrvs/opencrvs-core pull request #4098
Opened 2022-10-17 11:58 UTC by rabiulislamanik

2022-10-17 12:05 UTC, rabiulislamanik commented
@jpye-finch , @euanmillar  Please take a look at the videos I've added. While discussing with tameem, we were thinking if we could re-use the same intl-formatted labels used for desktop view (Cause we noticed that the labels for mobile devices were not intl-formatted )

2022-10-17 12:17 UTC, jpye-finch commented
@rabiulislamanik looks good! nice one

2022-10-25 08:38 UTC, jpye-finch commented
@euanmillar I guess we can then add this config option to form config. for a country to se true or not? 
@anny320 one for the backlog

2022-10-28 04:12 UTC, Zangetsu101 approved these changes

2022-10-31 05:50 UTC, Zangetsu101 requested changes
Some minor spellings

2022-10-31 05:50 UTC, Zangetsu101 commented on packages/client/src/i18n/messages/views/review.ts
> +  zeroDocumentsTextOForAnySection: {
```suggestion
  zeroDocumentsTextForAnySection: {
```

2022-10-31 05:50 UTC, Zangetsu101 commented on packages/client/src/i18n/messages/views/review.ts
> +    id: 'review.documents.zeroDocumentsTextOForAnySection'
```suggestion
    id: 'review.documents.zeroDocumentsTextForAnySection'
```

2022-10-31 08:54 UTC, Zangetsu101 approved these changes

2022-10-31 09:17 UTC, merged