Ocrvs 4141 systems
opencrvs/opencrvs-core pull request #4178
Opened 2022-10-30 12:31 UTC by KaliGreen

2022-10-31 12:28 UTC, naftis commented on packages/user-mgnt/src/features/system/handler.ts
> +      name: systemName,
nitpick: maybe we could just use "name: system.name" here to avoid the unnecessary repetition.

2022-10-31 12:28 UTC, naftis commented on packages/user-mgnt/src/features/system/handler.ts
> +    createdBy: createdBy,
nitpick: maybe we could just use "createdBy: system.createdBy" here to avoid the unnecessary repetition.

2022-10-31 12:30 UTC, naftis requested changes
small changes, otherwise looks good to me

2022-11-03 04:31 UTC, Zangetsu101 commented
@KaliGreen You might have _accidentally_ deleted the schema.d.ts file in gateway

2022-11-09 09:21 UTC, naftis approved these changes

2022-11-09 09:21 UTC, merged