locations api exposed
opencrvs/opencrvs-core pull request #4270
Opened 2022-11-14 07:30 UTC by kayumuzzaman

2022-11-16 07:38 UTC, Zangetsu101 requested changes

2022-11-16 07:38 UTC, Zangetsu101 commented on packages/gateway/src/features/restLocation/locationHandler.ts
> +    throw conflict(`statisticalID ${payload.statisticalID} is already exist`)
```suggestion
    throw conflict(`statisticalID ${payload.statisticalID} already exists`)
```

2022-11-16 07:38 UTC, Zangetsu101 commented on packages/gateway/src/features/restLocation/locationHandler.ts
> +    (partOfLocation !== null || partOfLocation !== '')
```suggestion
    Boolean(partOfLocation)
```

2022-11-16 07:38 UTC, Zangetsu101 commented on packages/gateway/src/features/restLocation/locationHandler.ts
> +}
these should be optional right?

2022-11-16 07:38 UTC, Zangetsu101 commented on packages/gateway/src/features/restLocation/locationHandler.ts
> +})
We should make these required as well.

2022-11-16 10:45 UTC, kayumuzzaman commented on packages/gateway/src/constants.ts
> +export const ORG_URL = 'http://opencrvs.org'
added to docker compose

2022-11-16 10:46 UTC, kayumuzzaman commented on packages/gateway/src/features/fhir/utils.ts
> +export const fetchFhirWithHearth = <T = any>(
fixed

2022-11-16 10:46 UTC, kayumuzzaman commented on packages/gateway/src/features/restLocation/locationHandler.ts
> +  }
removed

2022-11-16 10:46 UTC, kayumuzzaman commented on packages/gateway/src/features/restLocation/locationHandler.ts
> +})
fixed

2022-11-16 10:47 UTC, kayumuzzaman commented on packages/gateway/src/features/fhir/utils.ts
> +}
arise issue with response, so used `sendToFhir` instead of `fetchFHIR`

2022-11-16 14:22 UTC, Zangetsu101 approved these changes

2022-11-16 14:23 UTC, Zangetsu101 commented
@euanmillar The changes look good to me. Just give it a second look and we can merge this in

2022-11-21 21:39 UTC, euanmillar commented
Great work @kayumuzzaman !  Lets merge this.

2022-11-21 21:39 UTC, euanmillar approved these changes

2022-11-22 09:34 UTC, merged