Added customField handlebar name on config and redux template
opencrvs/opencrvs-core pull request #4285
Opened 2022-11-15 13:15 UTC by sadmananik

![Peek 2022-11-15 19-13](https://user-images.githubusercontent.com/36187489/201928818-12551b70-26f8-48f3-b0ff-9b141b54eef7.gif)

2022-11-16 08:23 UTC, Zangetsu101 commented
@euanmillar @jpye-finch We had to prepend the event and section name to the customFieldName to maintain their uniqueness.

2022-11-16 08:27 UTC, Zangetsu101 requested changes

2022-11-16 10:07 UTC, sadmananik commented on packages/client/src/forms/configuration/customUtils.ts
> +        operation: 'questionnaireToCustomFieldTemplateTransformer'
Yes. Just had to add a logic to differentiate when to add on the template object and  when on the section object

2022-11-16 10:14 UTC, sadmananik commented
> @Zangetsu101 @sadmananik regarding this - _"@euanmillar @jpye-finch We had to prepend the event and section name to the customFieldName to maintain their uniqueness."_, it sounds good to me however ...
> 
> What would we do in the edge case that a user creates 2 custom fields in the same section that are named exactly the same? Should we just ignore that edge case?

@euanmillar User can not create a custom field with the duplicate label. That was already implemented in the form config. It shows the error below while saving.

2022-11-17 12:56 UTC, Zangetsu101 approved these changes

2022-11-18 06:44 UTC, merged