ocrvs-4366: Delete integration
opencrvs/opencrvs-core pull request #4379
Opened 2022-11-30 11:22 UTC by sifulovi

[delete.webm](https://user-images.githubusercontent.com/11840131/204783391-2bea535a-3efc-4ef3-bb89-8d077f3e29ea.webm)

2022-12-02 05:48 UTC, Zangetsu101 commented on packages/user-mgnt/src/features/system/handler.ts
> +    }
```suggestion
    if (system) {
      logger.info(`System has been deleted by clientId ${clientId}`)
      return h.response(pickSystem(system)).code(200)
    }
```

2022-12-02 13:01 UTC, naftis commented on packages/client/src/views/SysAdmin/Config/Systems/Copy.tsx
> +    <TertiaryButton
We should rather use `<Button type="tertiary">`

2022-12-02 13:02 UTC, naftis commented on packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
> +  width: 100%;
i think we could achieve this with `<Stack>` component

2022-12-02 13:04 UTC, naftis requested changes
small changes but looks good otherwise

2022-12-05 12:27 UTC, naftis approved these changes

2022-12-05 12:28 UTC, merged