marriage event configuration
opencrvs/opencrvs-core pull request #4667
Opened 2023-02-06 12:59 UTC by kayumuzzaman

2023-02-14 06:38 UTC, Zangetsu101 requested changes

2023-02-14 06:38 UTC, Zangetsu101 commented on packages/migration/migrations/application-config/20230208081755-add-marriage-configuration.js
> +  )
wrap this in a withTransaction

2023-02-14 06:38 UTC, Zangetsu101 commented on packages/migration/migrations/application-config/20230208081755-add-marriage-configuration.js
> +  await db.collection('configs').updateMany({}, { $unset: { MARRIAGE: '' } })
Same for this as well

2023-02-14 11:27 UTC, kayumuzzaman commented on packages/migration/migrations/application-config/20230208081755-add-marriage-configuration.js
> +  )
refactored the migration

2023-02-16 05:43 UTC, Zangetsu101 approved these changes

2023-02-16 05:43 UTC, merged