Ocrvs 4357 - Issuing a certificate
opencrvs/opencrvs-core pull request #4713
Opened 2023-02-20 09:47 UTC by Nil20

2023-02-20 11:49 UTC, Zangetsu101 requested changes

2023-02-20 11:49 UTC, Zangetsu101 commented on packages/client/src/views/RecordAudit/ActionButtons.tsx
> +        <PrimaryButton
Let's use the newer Button instead

2023-02-20 12:27 UTC, Nil20 commented on packages/client/src/i18n/messages/constants.ts
> +  },
okay

2023-02-27 09:50 UTC, Zangetsu101 approved these changes

2023-02-27 09:50 UTC, merged