Certified webhook
opencrvs/opencrvs-core pull request #5050
Opened 2023-04-06 06:44 UTC by sadmananik

2023-04-13 10:43 UTC, euanmillar requested changes
Very small request @sadmananik .  Its working great apart from that

2023-04-13 10:43 UTC, euanmillar commented on packages/migration/migrations/openhim/20230405091629-add-webhook-on-certified.cjs
> +        name: 'Webhooks -> Birth Registration',
@sadmananik change name to: Webhooks -> Birth Certification

2023-04-13 10:43 UTC, euanmillar commented on packages/migration/migrations/openhim/20230405091629-add-webhook-on-certified.cjs
> +        name: 'Webhooks -> Death Registration',
As above: Webhooks -> Death Certification

2023-04-19 09:12 UTC, euanmillar requested changes
@sadmananik this is not right I am afraid. We want to keep everything else in the bundle as it is.  We just want to remove the DocumentReferences for certificates: "... that contain /ocrvs in string"

2023-04-25 05:58 UTC, Zangetsu101 commented
@euanmillar You are probably talking about the comment "Remove everything except task from bundle" right? Well with how it was previously the bundle had all the all the resources twice. This just stops pushing duplicates in the bundle

2023-04-25 07:11 UTC, euanmillar commented
@Zangetsu101 @sadmananik I will look into it again, but I had asked that the DocumentReference for certificate that is not base64 (the Minio URL DocumentReference) to be removed.  I asked @naftis to take a look yesterday and he said that the base64 DocRef was not in the bundle. Are you sure that this approach is deleting the correct duplicate?

2023-04-26 16:51 UTC, euanmillar commented
@sadmananik I am experiencing the same issue that Pyry encountered.  The certificate base64 is not arriving unless I do this: https://github.com/opencrvs/opencrvs-core/pull/5050/commits/b8e64ccd8eef46c10c5dc4f1cf9f0320adcf460f

2023-04-26 16:51 UTC, merged