serving application config from country-config
opencrvs/opencrvs-core pull request #5649
Opened 2023-07-11 13:35 UTC by jamil314

changing getConfig() and updateConfig() to include default config from country-config

2023-07-12 05:33 UTC, Zangetsu101 requested changes

2023-07-12 05:33 UTC, Zangetsu101 commented on packages/config/src/handlers/application/applicationConfigHandler.ts
> +    const res = await ApplicationConfig.updateOne(
We probably want to use `findOneAndUpdate` as `updateOne` returns a Result object instead of the updated document

2023-07-13 05:33 UTC, Zangetsu101 commented on packages/config/src/handlers/application/applicationConfigHandler.ts
> +    return h.response(applicationConfig).code(201)
We probably need to re-use the `getApplicationConfig` here as otherwise we aren't returning the total config from here

2023-07-13 06:17 UTC, Zangetsu101 approved these changes

2023-07-19 06:44 UTC, rikukissa commented on packages/config/src/handlers/application/applicationConfigHandler.ts
> +    return finalConfig
```suggestion
    const configFromDB = await ApplicationConfig.findOne({})
    const finalConfig = merge(
      configFromCountryConfig,
      configFromDB?.toObject()
    )
    return finalConfig
```

2023-07-19 06:45 UTC, rikukissa approved these changes

2023-07-19 12:43 UTC, merged