disable renaming of user roles
opencrvs/opencrvs-core pull request #5784
Opened 2023-08-18 13:02 UTC by Nil20

2023-08-30 07:23 UTC, naftis requested changes
Lets remove the button altogether like discussed here https://github.com/opencrvs/opencrvs-core/issues/5236

btw, lets link the issue in question to the description / title of these PR's. Makes reviewing easier to know why the PR has been made.

2023-09-05 05:09 UTC, Zangetsu101 approved these changes

2023-09-05 08:28 UTC, Zangetsu101 commented
@Nil20 Could you please try creating new user role and see if it still works because I think there were a couple of changes regarding the createRoles query with the seeding work

2023-09-07 12:24 UTC, Zangetsu101 approved these changes

2023-09-08 05:45 UTC, merged