validate-endpoint-workflow
opencrvs/opencrvs-core pull request #6156
Opened 2023-11-03 13:03 UTC by Nil20

2023-11-28 13:50 UTC, rikukissa commented on packages/client/src/transformer/index.ts
> +export function getChangedValues(
Very good improvement 👍

2023-11-28 14:19 UTC, rikukissa requested changes
Looking great! One thing I was expecting to find are the removal of the branches of the old event detection. Is that still in the works @Nil20 ?

2023-11-29 07:14 UTC, Nil20 commented on packages/commons/src/fhir/index.ts
> +
Yeah, correct! These don't have anything to do with fhir really. We can move them in the `record.ts`

2023-12-04 11:10 UTC, Zangetsu101 requested changes

2023-12-04 11:10 UTC, Zangetsu101 commented on packages/workflow/src/records/fhir.ts
> +          'http://opencrvs.org/specs/extension/contact-person-email'
There should be a similar extension for mobile number

2023-12-04 11:10 UTC, Zangetsu101 commented on packages/workflow/src/records/fhir.ts
> +      }
This value should come from the client payload

2023-12-04 11:10 UTC, Zangetsu101 commented on packages/workflow/src/records/state-transitions.ts
> +      }
```suggestion
      if (entry.resource.id !== previousTask.id) {
        return entry
      }
      return {
        ...entry,
        resource: updatedTaskWithLocationExtensions
      }
```

2023-12-04 11:10 UTC, Zangetsu101 commented on packages/workflow/src/records/state-transitions.ts
> +  const taskHistory = await getTaskHistory(currentCorrectionRequestedTask.id!)
This shouldn't be needed

2023-12-04 14:29 UTC, rikukissa commented
> > Looking great! One thing I was expecting to find are the removal of the branches of the old event detection. Is that still in the works @Nil20 ?
> 
> @rikukissa I think it would be better to remove them at the end when all the endpoints are done no?

Both are fine as long as they get removed 👍

2023-12-06 07:45 UTC, Zangetsu101 approved these changes

2023-12-06 07:46 UTC, merged