reinstate endpoint
opencrvs/opencrvs-core pull request #6398
Opened 2024-01-01 13:29 UTC by Nil20

2024-01-12 09:04 UTC, Zangetsu101 requested changes

2024-01-12 09:04 UTC, Zangetsu101 commented on packages/workflow/src/records/handler/reinstate.ts
> +) {
We should use the "createRoute" handler for reinstating, that way we can define which states we are expecting a record to be reinstated to

2024-01-17 13:34 UTC, Zangetsu101 commented on packages/gateway/src/features/registration/root-resolvers.ts
> +// }
Do we need this?

2024-01-17 13:34 UTC, Zangetsu101 commented on packages/workflow/src/records/audit.ts
> +  bundle: ValidRecord | SavedBundle,
Can we keep it as ValidRecord?

2024-01-17 13:34 UTC, Zangetsu101 commented on packages/workflow/src/records/handler/reinstate.test.ts
> +      },
This payload looks to be redundant

2024-01-17 13:34 UTC, Zangetsu101 commented on packages/workflow/src/records/handler/reinstate.test.ts
> +      },
Same for this one

2024-01-17 13:34 UTC, Zangetsu101 commented on packages/workflow/src/records/search.ts
> +  bundle: ValidRecord | SavedBundle,
let's try to keep it as ValidRecord

2024-01-17 13:34 UTC, Zangetsu101 commented on packages/workflow/src/records/state-transitions.ts
> +      ...(previousTask.extension || []),
we need to filter out the action extensions otherwise issues might crop up

2024-01-17 13:34 UTC, Zangetsu101 commented on packages/workflow/src/states.ts
> +      ReadyForReviewRecord | RegisteredRecord
This should be reciprocal to the archived transition

2024-01-17 13:37 UTC, Nil20 commented on packages/gateway/src/features/registration/root-resolvers.ts
> +// }
Nope

2024-01-23 12:49 UTC, Zangetsu101 approved these changes

2024-01-24 07:56 UTC, merged