Update setup script
opencrvs/opencrvs-core pull request #6555
Opened 2024-02-28 11:50 UTC by Nil20

2024-02-29 14:06 UTC, rikukissa approved these changes

2024-02-29 14:08 UTC, rikukissa approved these changes

2024-02-29 14:11 UTC, rikukissa requested changes
How about the docker-compose requirement? https://github.com/opencrvs/opencrvs-core/issues/6534#issuecomment-1968836320

2024-02-29 14:41 UTC, Nil20 commented
> How about the docker-compose requirement? https://github.com/opencrvs/opencrvs-core/issues/6534#issuecomment-1968836320

We have docker-compose on this version. So, I don’t think, we need to update it for docker compose.

2024-03-04 06:50 UTC, Zangetsu101 commented
@Nil20 In that case could you please open up a PR for v1.5.0 (i.e. develop) with the necessary changes?

2024-03-04 12:36 UTC, rikukissa approved these changes

2024-03-04 12:39 UTC, merged