[State transitions] Remove detect event
opencrvs/opencrvs-core pull request #6563
Opened 2024-03-01 10:05 UTC by Nil20

2024-03-07 07:55 UTC, Zangetsu101 requested changes
@Nil20 gateway is also probably using openhim url & a couple of other services most likely. The easiest way to look for them would be to search for the port "5001" in both core & farajaland

2024-03-07 07:55 UTC, Zangetsu101 commented on packages/workflow/src/features/registration/utils.test.ts
>    it('Generates proper birth tracking id successfully', async () => {
```suggestion
  it('Generates proper birth tracking id successfully even if countryconfig returns 404', async () => {
```

2024-03-11 06:12 UTC, Zangetsu101 commented on packages/workflow/src/features/registration/handler.test.ts
> +import { URLReference } from '@workflow/../../commons/build/dist/types'
import looks a bit weird

2024-03-11 06:50 UTC, Nil20 commented on packages/user-mgnt/src/features/createUser/handler.test.ts
> -
My bad. Instead of updating the fhirUrl, removed the test.

2024-03-11 11:36 UTC, Zangetsu101 approved these changes

2024-03-11 11:38 UTC, merged