[OCRVS 6971] Image compression reduction configuration
opencrvs/opencrvs-core pull request #7019
Opened 2024-05-20 12:07 UTC by tahmidrahman-dsi

2024-05-20 13:39 UTC, Zangetsu101 requested changes

2024-05-20 13:39 UTC, Zangetsu101 commented on packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
> +        props.onUploadingStateChanged(true)
```suggestion
        props.onUploadingStateChanged(false)
```

2024-05-20 13:39 UTC, Zangetsu101 commented on packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
> +      props.onUploadingStateChanged(true)
```suggestion
      props.onUploadingStateChanged(false)
```

2024-06-03 06:24 UTC, Zangetsu101 approved these changes

2024-06-06 06:12 UTC, Zangetsu101 commented
@tahmidrahman-dsi Could you please add a changelog for this PR and briefly explain there what the 2 new field properties enable for us?

2024-06-10 07:05 UTC, tahmidrahman-dsi commented
> @tahmidrahman-dsi Could you please add a changelog for this PR and briefly explain there what the 2 new field properties enable for us?

@Zangetsu101 done https://github.com/opencrvs/opencrvs-core/pull/7019/commits/c9ff82f8e4f55bf3b6448d5667f537aa1219c69b

2024-06-10 08:02 UTC, Zangetsu101 approved these changes

2024-06-10 08:06 UTC, merged