change serving country certificates
opencrvs/opencrvs-core pull request #7521
Opened 2024-08-21 12:18 UTC by Nil20

Country config PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/250

We can token protect the farajaland `certificate` routes like in the farajaland PR which seems like a much simpler approach than creating presigned url like we discussed [here](https://github.com/opencrvs/opencrvs-core/issues/7156#issuecomment-2259938605).

2024-08-26 05:44 UTC, rikukissa commented
Indeed, seems like a better approach 👍

2024-08-26 05:49 UTC, rikukissa commented
@Zangetsu101 could you also review this please?

2024-08-27 10:43 UTC, Nil20 commented
We can update the changelog in this [PR](https://github.com/opencrvs/opencrvs-core/pull/7352)

2024-08-27 13:11 UTC, Zangetsu101 requested changes

2024-08-27 13:11 UTC, Zangetsu101 commented on packages/client/src/components/interface/Navigation.tsx
> -                          />
We don't want to remove the `integrations` nav item no?

2024-08-27 13:11 UTC, Zangetsu101 commented on packages/client/src/offline/reducer.ts
> +>
```suggestion
export type CertificatePayload = {
  svgCode: string
  event: Event
}
```

2024-08-27 13:11 UTC, Zangetsu101 commented on packages/client/src/offline/reducer.ts
> +  return fetchedCertificates
Do we even need these two? They are basically identity functions :thinking:

2024-08-27 13:11 UTC, Zangetsu101 commented on packages/client/src/offline/reducer.ts
I think we can simplify the reducer quite a bit now

2024-08-28 10:22 UTC, Zangetsu101 approved these changes

2024-08-28 11:18 UTC, Nil20 commented
> Indeed, seems like a better approach for now 👍 Could you please confirm the certificates also still work offline?

Yep. It does.

2024-08-28 11:40 UTC, Zangetsu101 approved these changes

2024-08-28 14:07 UTC, merged