fix: custom time period in user audit
opencrvs/opencrvs-core pull request #7810
Opened 2024-10-22 06:48 UTC by jamil314

Picked last date of a month for `dateEnd` when picking date range so that the entries of last selected month is included.

2024-10-23 06:21 UTC, tahmidrahman-dsi requested changes

2024-10-23 06:21 UTC, tahmidrahman-dsi commented on packages/client/src/components/DateRangePicker.tsx
> +              label === 'From'
@jamil314  I am afraid label matching may not work with other locales. I can think of one way that you can provide different distinctive id names for start and end month selector components to differentiate.

2024-10-30 07:55 UTC, Zangetsu101 approved these changes

2024-10-30 10:38 UTC, tahmidrahman-dsi approved these changes

2024-10-30 10:38 UTC, merged