feat: Add constants.humanName to allow countries to have custom full name format
opencrvs/opencrvs-core pull request #7957
Opened 2024-11-12 09:17 UTC by Siyasanga

In order to allow countries to define their own full name format, we are adding a constants.humanName into the client.csv translations, which will then be used everywhere where we are displaying system users and citizen's name in the systems.

Addresses https://github.com/opencrvs/opencrvs-core/issues/6830

2024-11-22 06:34 UTC, Zangetsu101 requested changes
@Siyasanga After taking a look at the changes made to the e2e tests, I would say it's better to change all those places in core to use the new format instead. As if only some of the places use the new format, then it would just create confusion

2025-01-21 13:11 UTC, Zangetsu101 commented on packages/client/src/utils/draftUtils.test.ts
> +)
Is this supposed to be like so?

2025-01-22 08:34 UTC, Siyasanga commented on packages/client/src/utils/draftUtils.test.ts
> +)
Nice catch, thanks Tameem. Fixed

2025-01-24 14:22 UTC, euanmillar commented
@Zangetsu101 @Siyasanga and I dont know why knip is failing here but tests are all passing and think this is ready to merge?

2025-01-24 14:22 UTC, euanmillar approved these changes

2025-01-27 06:04 UTC, Zangetsu101 commented
@Siyasanga What's the status of e2e tests? As long as they are passing, we can merge this in

2025-01-27 10:01 UTC, Siyasanga commented
> @Siyasanga What's the status of e2e tests? As long as they are passing, we can merge this in

They are passing so I will merge this and the related [contry-config PR](https://github.com/opencrvs/opencrvs-countryconfig/pull/314)

2025-01-27 13:09 UTC, Zangetsu101 approved these changes

2025-01-27 13:09 UTC, Zangetsu101 commented on CHANGELOG.md
> +- Introduced a new customisable UI component: Banner [#8276](https://github.com/opencrvs/opencrvs-core/issues/8276)
```suggestion
```

2025-01-27 13:09 UTC, Zangetsu101 commented on CHANGELOG.md
> +- Introduced a new customisable UI component: Banner [#8276](https://github.com/opencrvs/opencrvs-core/issues/8276)
Seems to be something irrelevant

2025-01-27 13:09 UTC, merged