fix ui issues with Action Menu
opencrvs/opencrvs-core pull request #8163
Opened 2024-12-05 11:42 UTC by jpye-finch

Fixes ui issues in Action menu
- icon sizes
- dropdown styling
- replaces deprecated ResponsiveModel with Dialog
- replaces deprecated PrimaryButton etc with Button
- adds icon right positioning option

2024-12-09 06:58 UTC, Zangetsu101 commented on packages/client/src/views/RecordAudit/ActionMenu.tsx
> +          <Button type="primary" size="medium" iconPosition="right">
@jpye-finch The Button component shouldn't really concern itself where the icon is being positioned. I'll remove it and see if I can just replicate the same using flex

2025-02-06 21:25 UTC, jpye-finch commented
will be fixed next week

2025-02-12 07:22 UTC, naftis commented on packages/client/src/views/RecordAudit/ActionMenu.tsx
> +          <Button type="primary" size="medium" iconPosition="right">
It already kinda does as it wants to align the SVG for it to look nice. We modified this a little bit - it should be quite easy to use now, button with icon is fairly common with our recent designs. Removed the iconPosition and just added proper `gap` with display flex.

2025-03-10 06:06 UTC, Zangetsu101 requested changes

2025-03-10 06:06 UTC, Zangetsu101 commented on packages/client/src/views/RecordAudit/ActionMenu.tsx
> +        <DropdownMenu.Trigger>
```suggestion
        <DropdownMenu.Trigger asChild>
```
We need the `asChild` prop here for proper DOM element hierarchy

2025-03-11 05:55 UTC, Zangetsu101 approved these changes

2025-03-28 12:41 UTC, merged