feat: implement `getInitialValue` and `fieldValueToString`
opencrvs/opencrvs-core pull request #8255
Opened 2024-12-26 06:57 UTC by jamil314

2024-12-27 10:35 UTC, Zangetsu101 requested changes

2024-12-27 10:35 UTC, Zangetsu101 commented on packages/client/src/v2-events/components/forms/utils.ts
> +}
let's not mutate the input

2024-12-27 10:35 UTC, Zangetsu101 commented on packages/client/src/v2-events/features/events/components/Pages.tsx
> +  setFormValues(eventId, initialValues)
Let's be a bit more explicit on when we want to run this, something like: 
```ts
if (!equal(inititalValues, formValues) {
  setFormValues(eventId, inititalValues)
}
```

2024-12-27 12:54 UTC, Zangetsu101 approved these changes

2025-01-03 02:58 UTC, rikukissa commented on packages/client/src/v2-events/components/forms/utils.ts
> +}
Let's move these and the logic in `fieldValueToString` to the registered field component files.

```
export const initialValue = <value>
```

We should also consider if we need initial values to be definited like this at all or if all registered components should assume "undefined" as the initial empty value. I'm saying this because for instance an empty string `""` is not the same as "user didn't input anything" as cleaning they might have written something to the input and then decided to make it empty

2025-01-07 04:12 UTC, merged